version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\peter-wangxu\goock

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d -v -t ./...
  - go build -v

build_script:
  - go test -v -race ./...